# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
platform :ios, "7.1"

target "ShoutApp" do
pod 'UIAlertView+Blocks'
pod 'AFNetworking', '~> 2.0'
end

target "ShoutAppTests" do

end

